# DQNAgent configuration
model_name: "dqn"
runner_type: "reinforcement"

# Hyperparameters
action_dim: 4  # Default for testing
lr: 0.00025
batch_size: 32
gamma: 0.99
buffer_capacity: 100000
target_update_freq: 1000
epsilon_start: 1.0
epsilon_end: 0.1
epsilon_decay: 1000000
