# SARSAAgent configuration
model_name: "sarsa"
runner_type: "reinforcement"

# Hyperparameters
action_dim: 4
lr: 0.00025
gamma: 0.99
epsilon_start: 1.0
epsilon_end: 0.1
epsilon_decay: 1000000
device: "cpu"
