# TD3Agent configuration
model_name: "td3"
runner_type: "reinforcement"

# Hyperparameters
action_dim: 1
lr: 0.0003
batch_size: 256
gamma: 0.99
tau: 0.005
policy_delay: 2
noise_clip: 0.5
policy_noise: 0.2
buffer_capacity: 1000000
device: "cpu"
